name: Run shellcheck

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Run shellcheck
        run: |
          find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck
